# work flow name
name: 'sample jobs'
# trigger
on: [push]

# job
jobs:
  sample_job_01:
    name: Job Run Test 01
    runs-on: ubuntu-latest
    steps: 
      - name: hello world #ステップ名
        run: echo "hello world!!" #実行したいコマンドを記述する